CREATE TABLE  `activePlantRecord` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `fieldName` VARCHAR(30) NOT NULL,
  `activePlantDate` datetime NOT NULL default CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;