CREATE TABLE  `disaster` (
  `disasterId` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `disasterName` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`disasterId`) USING BTREE,
  UNIQUE KEY `UNI_FIELDNAME` (`disasterName`)
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;