CREATE TABLE  `field` (
  `fieldId` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `fieldName` VARCHAR(30) NOT NULL,
  `other` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`fieldId`) USING BTREE,
  UNIQUE KEY `UNI_FIELDNAME` (`fieldName`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;