CREATE TABLE location (
  locationId INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (locationId) USING BTREE,
  locationName VARCHAR(30) NOT NULL,
  UNIQUE KEY UNI_FIELDNAME (locationName),
  other VARCHAR(100) NOT NULL
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;