CREATE TABLE  natDis (
  natDisId INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`natDisId`) USING BTREE,
  natDisName VARCHAR(30) NOT NULL,
  UNIQUE KEY `UNI_NATDISNAME` (`natDisName`)
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;