CREATE TABLE  petDisSpec (
  petDisSpecId INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`petDisSpecId`) USING BTREE,
  petDisSpecName VARCHAR(30) NOT NULL,
  UNIQUE KEY `UNI_PDSNAME` (`petDisSpecName`)
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;