CREATE TABLE  petDis (
  petDisId INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`petDisId`) USING BTREE,
  petDisName VARCHAR(30) NOT NULL,
  UNIQUE KEY `UNI_NATDISNAME` (`petDisName`)
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;