CREATE TABLE  petDisSpec (
  petDisSpecId INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`petDisSpecId`) USING BTREE,
  petDisSpecName VARCHAR(30) NOT NULL,
  UNIQUE KEY `UNI_PDSNAME` (`petDisSpecName`),
  type VARCHAR(10),
  alias VARCHAR(10),
  severity INT(10),
  commonImpactonYield INT(10),
  maxImpactonYield INT(10),
  preventionorRemedy VARCHAR(10),
  indvidualorGroup VARCHAR(10),
  impactedArea VARCHAR(10),
  color VARCHAR(10),
  shape VARCHAR(10),
  description VARCHAR(200),
  sympthon VARCHAR(200),
  forms VARCHAR(200),
  habits VARCHAR(200),
  rules VARCHAR(200),
  pictureIds VARCHAR(200)
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;