CREATE TABLE petSolu (
  petSoluId INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (petSoluId) USING BTREE,
  petSoluName VARCHAR(30) NOT NULL,
  cure TINYINT(1) DEFAULT 1,
  petDisSpecId int(10) unsigned not null,
  KEY FK_PSPDS_ID (petDisSpecId),
  CONSTRAINT FK_PSPDS_ID FOREIGN KEY (petDisSpecId)
  REFERENCES petDisSpec (petDisSpecId) ON DELETE CASCADE ON UPDATE CASCADE,
  other VARCHAR(100) NOT NULL
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;