CREATE TABLE subStage (
  subStageId INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (subStageId) USING BTREE,
  subStageName VARCHAR(30) NOT NULL,
  stageName VARCHAR(30) NOT NULL,
  UNIQUE KEY UNI_SUBSTAGENAME (subStageName)
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;