CREATE TABLE user (
  userId INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (userId) USING BTREE,
  userName VARCHAR(30) NOT NULL,
  UNIQUE KEY UNI_SUBSTAGENAME (userName),
  password VARCHAR(30) NOT NULL,
  cellPhone VARCHAR(30) NOT NULL,
  address VARCHAR(30) NOT NULL
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;