CREATE TABLE  variety (
  varietyId INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`varietyId`) USING BTREE,
  varietyName VARCHAR(30) NOT NULL,
  UNIQUE KEY `UNI_VARIETYNAME` (`varietyName`),
  cropId int(10) unsigned not null,
  KEY FK_TRANSACTION_CROP_ID (cropId),
  CONSTRAINT FK_TRANSACTION_CROP_ID FOREIGN KEY (cropId)
  REFERENCES crop (cropId) ON DELETE CASCADE ON UPDATE CASCADE,
  other VARCHAR(100) NOT NULL
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;